### ISSUE TITLE
I am having some trouble in authentication

### ISSUE THREAD

**Issue by harshdamaniahd** [koltyakov/sp-auth-puppeteer-sample#2]
```
{ RequestError: Error: connect ETIMEDOUT 20.190.129.163:443
    at new RequestError (C:\test9\sp-auth-puppeteer-sample-master\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\test9\sp-auth-puppeteer-sample-master\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\test9\sp-auth-puppeteer-sample-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\test9\sp-auth-puppeteer-sample-master\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\test9\sp-auth-puppeteer-sample-master\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT 20.190.129.163:443',
  cause:
   { Error: connect ETIMEDOUT 20.190.129.163:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '20.190.129.163',
     port: 443 },
  error:
   { Error: connect ETIMEDOUT 20.190.129.163:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '20.190.129.163',
     port: 443 },
  options:
   { simple: false,
     strictSSL: false,
     json: true,
     form: { login: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' },
     uri: 'https://login.microsoftonline.com/GetUserRealm.srf',
     method: 'POST',
     callback: [Function: RP$callback],
     transform: undefined,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

```

**Comment by koltyakov** [comment]
Looks that you're behind a corporate proxy. Node.js needs [some environment variables](https://github.com/s-KaiNet/gulp-spsave/issues/23#issuecomment-278863914) configuration to support a specific network environment.

**Comment by harshdamaniahd** [comment]
I did set the environment variable in windows cmd :
set https_proxy=http://********
set http_proxy=http://**********'
set NODE_TLS_REJECT_UNAUTHORIZED=0

but still it doesnt work.
Do i have to change anything in code ?

**Comment by koltyakov** [comment]
Nope, ETIMEDOUTs are network-related. I've seen a number of the issues with that message, it was always network and proxy.
